# Site settings
title: Hide in my shell
email: mihaly@koles.hu
description: Mostly photos, some techy posts.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://koles.hu" # the base hostname & protocol for your site
title_description: Mostly photos, some techy posts. Not so personal.
#blog logo
logo: "/assets/images/avatar.jpg"
# blog cover
cover: "/assets/images/cover.jpg"
google_analytics: UA-2775446-4
disqus_shortname: hideinmyshell
github_repository: https://nyuwec.github.io

author:
  name: 'Mihály Köles'
  email: 'mihaly@koles.hu'
  twitter_username: 'nyuwec'
  github_username: 'nyuwec'
  linkedin_username: 'mihalykoles'
  500px_username: 'kolesm'
  unsplash_username: 'mihaly_koles'

# social icons and sharing options
social:
  - icon:	instagram
    url:	https://instagram.com/kolesm
    desc:	Check my humble photos
    share_url:
    share_title:
    share_link:

  # - icon:	500px
  #   url:	https://500px.com/kolesm
  #   desc:	Check my "professional" photos
  #   share_url:
  #   share_title:
  #   share_link:

  - icon:	linkedin
    url:	http://www.linkedin.com/in/mihalykoles
    desc:	Linkedin profile
    share_url:
    share_title:
    share_link:

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
